# hash:sha256:db203e596ef34e55015e64a6c4717ab36f3611c8ebb1acae7d5911df7f419b0d
FROM registry.co.aionlabs.com/codeocean/mambaforge3:22.11.1-4-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip3 install -U --no-cache-dir \
    graphviz==0.21 \
    networkx==3.1 \
    pandas==2.2.3 \
    pillow==11.1.0 \
    plotly==6.0.1 \
    pydot==4.0.1 \
    pytest==7.4.3 \
    scipy==1.15.2 \
    statsmodels==0.14.4 \
    streamlit==1.48.0 \
    typer==0.9.0
